### ISSUE TITLE
How to make a choice between NeuroSpeech.Workflows and NeuroSpeech.Eternity?

### ISSUE THREAD

**Issue by send2vinnie** [neurospeech/eternity#11]
The features of both NeuroSpeech.Workflows and NeuroSpeech.Eternity look quite closed. Do you have the guideline for how to choose which to use in terms of scalability, stability and business scenarios?

**Comment by ackava** [comment]
NeuroSpeech.Workflows was a syntax sugar built on top of Microsoft's DurableTasks. But we dropped it and we are no longer developing on it. Since DurableTasks always stay in the memory so you cannot create tasks that span days/months/years.... . You can use it on top of DurableTasks, but which is very heavy and very difficult to debug and unit test. If you are using DurableTasks, then you can use Workflows on top of it, we recommend using source and build your own code.

NeuroSpeech.Eternity was built from scratch, and it is very lightweight compared to Workflows. It is unit testable and it does not depend upon DurableTasks. Eternity has its own independent lightweight abstract storage which makes it easy to use it even on Xamarin Mobile Applications.
